name: VisionSite
favicon: null
layout_spectrum: 0.6053233249112964
typography_spectrum: 0.19287441298365593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c2c7cb'
    - '#030502'
    - '#016d22'
    - '#0997dd'
  brandStrength: 0.5
  lightness: 0.09853839594870806
  saturation: 0.5056702073197812
  rhythmicContrast: 0
purpose: []
